# Generated by Django 5.0.3 on 2024-05-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_logo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_type',
        ),
    ]
