# Generated by Django 5.0.3 on 2024-05-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_student_address_remove_student_hobby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guradian',
            name='gmob',
        ),
    ]
